# Generated by Django 3.1.3 on 2021-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startBid',
            new_name='start_Bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to='static/auction_photos'),
        ),
    ]
