# Generated by Django 3.1.3 on 2021-10-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211030_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_Bid',
            new_name='startBid',
        ),
    ]
