# Generated by Django 3.1.3 on 2021-10-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211030_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='auctions.Category'),
        ),
    ]
