# Generated by Django 3.1.3 on 2021-10-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211030_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(related_name='listings', to='auctions.Category'),
        ),
    ]
