# Generated by Django 3.1.3 on 2022-02-01 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211031_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
